---

- name: Test distribution
  assert:
    that: >
      ansible_os_family == "RedHat"

- name: Create YUM repo file
  yum_repository:
    name: mongodb
    description: MongoDB YUM repo
    baseurl: "{{ mongodb_yumrepo_url }}"
    gpgcheck: no
    params: "{{ mongodb_yumrepo_params }}"
  tags:
    - mongodb_pkg

- name: Install MongoDB pacakges for RedHat
  package:
    name: "{{ item }}"
  with_items: "{{ mongodb_pkgs }}"
  notify:
    - Restart mongod service
  tags:
    - mongodb_pkg

- name: Create MongoDB sysconfig file
  template:
    src: mongod.sysconfig.j2
    dest: "{{ mongodb_sysconfig_file }}"
  notify:
    - Restart mongod service
  tags:
    - mongodb_config

- name: Create main MongoDB config file
  template:
    src: mongod.conf.j2
    dest: "{{ mongodb_config_file }}"
  notify:
    - Restart mongod service
  tags:
    - mongodb_config

- name: Enable MongoDB service
  service:
    name: "{{ mongodb_service_name }}"
    enabled: yes
  tags:
    - mongodb_service

- name: Start MongoDB service
  service:
    name: "{{ mongodb_service_name }}"
    state: started
  register: mongodb_service_started
  tags:
    - mongodb_service
