---

- name: Restart mongod service
  service:
    name: "{{ mongodb_service_name }}"
    state: restarted
  when: >
    mongodb_service_started is not defined or
    not mongodb_service_started.changed
